export enum Direction {
  BUY = "BUY",
  SELL = "SELL",
}

export enum ActionType {
  BINANCE_LOGIN = "BINANCE_LOGIN",
  BINANCE_BALANCE = "BINANCE_BALANCE",
  BINANCE_PLACE_BUY_ORDER = "BINANCE_PLACE_BUY_ORDER",
  BINANCE_PLACE_SELL_ORDER = "BINANCE_PLACE_SELL_ORDER",
  BINANCE_SUBSCRIBE_ORDER_BOOK = "depthUpdate",
}
