export enum Pairs {
  BTCUSDT = "BTCUSDT",
  ETHUSDT = "ETHUSDT",
  BNBUSDT = "BNBUSDT",
  SOLUSDT = "SOLUSDT",
  LINKUSDT = "LINKUSDT",
  ADAUSDT = "ADAUSDT",
  DOGEUSDT = "DOGEUSDT",
  DOTUSDT = "DOTUSDT",
  XRPUSDT = "XRPUSDT",
}
