export enum Pairs {
  BTCUSDT = "BTCUSDT",
  ETHUSDT = "ETHUSDT",
  BNBUSDT = "BNBUSDT",
  SOLUSDT = "SOLUSDT",
  LINKUSDT = "LINKUSDT",
  ADAUSDT = "ADAUSDT",
  DOGEUSDT = "DOGEUSDT",
  DOTUSDT = "DOTUSDT",
  XRPUSDT = "XRPUSDT",
}

export enum Exchanges {
  BINANCE = "BINANCE",
  BYBIT = "BYBIT",
  OKX = "OKX",
  MEXC = "MEXC",
  BINGX = "BINGX",
}
